Fix bitmap font loader to load fonts with random placed args into <info> tag in 5.4.0-rc.2
pixijs/pixi.js pull request #7021
Opened 2020-11-22 14:40 UTC by SerG-Y

##### Description of change

Fix #7008 
- For BitmapFont text format that's XML-based check if <font> tag exist than parse as XML and check if needed tags exist
- Added test for case when arg into <info> tag placed randomly

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

2020-11-22 17:27 UTC, bigtimebuddy requested changes
Small change, otherwise looks good @SerG-Y

2020-11-22 17:27 UTC, bigtimebuddy commented on packages/text-bitmap/src/formats/XMLStringFormat.ts
> +        if (typeof data === 'string' && data.includes('<font>'))
Could you use `indexOf` instead of `includes`, since `includes` [is not ES5](https://caniuse.com/es6-string-includes) and not supported on IE11.

2020-11-22 19:59 UTC, bigtimebuddy approved these changes
Nice work :+1:

2020-11-24 01:45 UTC, andrewstart approved these changes

2020-11-24 05:09 UTC, merged

2020-11-24 05:12 UTC, bigtimebuddy commented
Thanks @SerG-Y! Feel free to [submit an expense](https://opencollective.com/pixijs/expenses/new) to Open Collective for $25 for solving this bug.