Fix: TilingSprite uvRespectAnchor = false mode.
pixijs/pixi.js pull request #7105
Opened 2020-12-26 17:38 UTC by SukantPal

Fixes #7098 

##### Description of change

Apply the "shift matrix" in case of `uvRespectAnchor` being false as described in the (newly added) implementation notes. The local space rect being drawn is now always (-anchor.x * W, -anchor.y * H, W, H) (i.e. equal to the local bounds of the tiling sprite).

I'll make a demo once the CI passes.

2020-12-27 04:33 UTC, bigtimebuddy approved these changes
👏

2020-12-27 21:59 UTC, bigtimebuddy commented
@SukantPal Your PR looks like the correct implementation. And this may be another bug, but there's still an inconsistency with WebGL still. Here's the WebGL version, it doesn't respect uvRespectAnchor. Do you know why that is?
https://jsfiddle.net/bigtimebuddy/a0vy8mbq/

2020-12-27 23:32 UTC, ivanpopelyshev requested changes
Seriously, what the heck, how did I miss this?

In TilingSpriteRenderer, we have `if (uvRespectAnchor)` - need to add `else` there and put usual default uvs from `QuadUV` back there.

I also recommend this PR to be applied to 3.5

2020-12-27 23:32 UTC, ivanpopelyshev commented on packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
> +    patternMatrix.prepend(lt);
why not copyFrom() instead of identity?

2020-12-27 23:36 UTC, SukantPal commented on packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
> +    patternMatrix.prepend(lt);
Fair enough

2020-12-29 02:32 UTC, SukantPal commented on packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
> +    patternMatrix.prepend(lt);
Done 👍

2020-12-29 13:32 UTC, ivanpopelyshev approved these changes
Perfect!

2020-12-29 19:09 UTC, merged

2020-12-29 19:09 UTC, bigtimebuddy commented
Big thanks @SukantPal!