Add Generics to Texture, BaseTexture for Resource types
pixijs/pixi.js pull request #7246
Opened 2021-02-15 17:51 UTC by bigtimebuddy

This adds an opt-in stricter type for Texture and BaseTexture using Generics.

Here are some uses cases:

### Better Return Values Using `from`
```js
// current
const texture = Texture.from('path/to/image.png');
const url = (texture.baseTexture.resource as ImageResource).url;

// new!
const texture = Texture.from<ImageResource>('path/to/image.png');
const url = texture.baseTexture.resource.url;
```

### More Casting Flexibility
```js
// current
const url = (sprite.texture.baseTexture.resource as ImageResource).url;

// new!
const texture = sprite.texture as Texture<ImageResource>;
const url = texture.baseTexture.resource.url;
```

### Stricter Resource Option Types

```js
// current
const base = BaseTexture.from("path/to/image.svg", {
  resourceOptions: { anything: 'goes' } // <-- NO TYPE CHECKING HERE
});

// new!
const base = BaseTexture.from<SVGResource, ISVGResourceOptions>("path/to/image.svg", {
  resourceOptions: { } // <-- ONLY VALID ISVGResourceOptions
});
```

2021-02-15 18:09 UTC, bigtimebuddy commented on packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
> +import { Texture } from '@pixi/core';
I don't know how this was missed 👀

2021-02-15 18:10 UTC, bigtimebuddy commented on packages/mesh-extras/src/SimpleMesh.ts
> +        texture: Texture = Texture.EMPTY,
This change was required, because type inference was being used. Which, IMO, is more of a case for not inferring in situations like this (params).

2021-02-15 20:34 UTC, SukantPal requested changes

2021-02-15 20:34 UTC, SukantPal commented on packages/core/src/textures/BaseTexture.ts
>   * @memberof PIXI
webdoc doesn't have it currently, but type parameters will be documented with `@typeParam`. Let's add them right now!

```suggestion
 * @memberof PIXI
 * @typeParam T - The base-texture's resource.
 * @typeParam U - The resource parameters.
```

2021-02-15 21:18 UTC, GoodBoyDigital approved these changes
This is awesome! _I love generics_ 

Just throwing this out there, but how do you feel about using more descriptive generics rather than T? Like `RESOURCE_TYPE` make it much easier to quickly understand what the generic is and what it's for?

2021-02-15 21:19 UTC, SukantPal commented
@GoodBoyDigital I think `R` would suffice.

2021-02-15 21:25 UTC, GoodBoyDigital commented
I never quite got why the generic props are single letter. Always found it a bit strange as I feel it makes it harder to understand whats going on when looking at code. 

But having said that the typescript world tends not to agree with me! I guess the risk is the code ends up getting overly verbose and a bit too wordy! 

Potato patato :)

2021-02-16 03:35 UTC, bigtimebuddy commented
Thanks guys. 

* @SukantPal I added the docs.
* @GoodBoyDigital I renamed `T` to `R` for "Resource" and `U` to `RO` for "Resource Options"

2021-02-16 15:36 UTC, SukantPal approved these changes
Superb!

2021-02-16 20:30 UTC, merged