Fixed Parent type for Container
pixijs/pixi.js pull request #7248
Opened 2021-02-17 09:36 UTC by JetLua

pixi.js@6.0.0-rc.2

```ts
class A extends PIXI.Container {
  constructor() {
    super()
    // There is no 'addChild' method
    this.parent.addChild
  }
}
```

2021-02-17 14:43 UTC, bigtimebuddy approved these changes

2021-02-18 03:25 UTC, SukantPal requested changes
Superb!

2021-02-18 03:25 UTC, SukantPal approved these changes
Sometimes my hand betrays me and clicks on the wrong button. Approve ✅!

2021-02-18 03:39 UTC, merged

2021-02-18 03:40 UTC, bigtimebuddy commented
Thanks @JetLua