Add multisample shortcut and parameters
pixijs/pixi.js pull request #7440
Opened 2021-04-22 19:44 UTC by dev7355608

##### Description of change

- Added getter and setter shortcut for `renderTexture.framebuffer.multisample`.
- Added multisample option to `RenderTexture.create()` and `RenderTexture`/`BaseRenderTexture` constructors.
- Added multisample parameter to `AbtractRenderer.generateTexture()`.

##### Pre-Merge Checklist

- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

2021-04-22 21:14 UTC, bigtimebuddy requested changes
Don't have any problem overall with adding some of these new options. Just some comments where we don't need to supported this on deprecated implementations.

2021-04-22 21:14 UTC, bigtimebuddy commented on packages/core/src/renderTexture/BaseRenderTexture.ts
> +            const multisample = arguments[4];
This isn't necessary, backward compatibility not needed in this case)

2021-04-22 21:14 UTC, bigtimebuddy commented on packages/core/src/renderTexture/RenderTexture.ts
> +        multisample?: MSAA_QUALITY): RenderTexture;
Same, please don't add more to deprecated methods. The approach here is object-based param.

2021-04-22 21:14 UTC, bigtimebuddy commented on packages/core/src/renderTexture/RenderTexture.ts
> +                multisample: rest[3],
Unnecessary.

2021-04-29 15:06 UTC, ivanpopelyshev approved these changes
Looks good!

2021-04-29 21:30 UTC, bigtimebuddy approved these changes

2021-05-05 16:34 UTC, bigtimebuddy commented
@dev7355608 could you resolve conflicts with your other PR?

2021-05-05 21:03 UTC, merged

2021-05-05 21:03 UTC, bigtimebuddy commented
Thank you @dev7355608 super useful shortcuts APIs here.